export enum roleType {
    SUPER_ADMIN = 'super_admin',
    UNIVERSITY = 'university',
    DEPARTMENT = 'department',
    UNIVERSITY_STAFF = 'university_staff',
    DEPARTMENT_STAFF = 'department_staff',
    STUDENT = 'student',
    INSTITUTION = 'institution',
    MENTOR = 'mentor',
    STUDENT_AMBASSADOR = 'student_ambassador',
    INSTITUTION_STAFF = 'institution_staff',
}

export enum permissionType {
    ADD_RESEARCH_NEWS = 'ADD_RESEARCH_NEWS',
    EDIT_RESEARCH_NEWS = 'EDIT_RESEARCH_NEWS',
    DELETE_RESEARCH_NEWS = 'DELETE_RESEARCH_NEWS',
    VIEW_RESEARCH_NEWS = 'VIEW_RESEARCH_NEWS',

    VIEW_UNIVERSITY_PROFILE = 'VIEW_UNIVERSITY_PROFILE',
    EDIT_UNIVERSITY_PROFILE = 'EDIT_UNIVERSITY_PROFILE',

    ADD_SCHOLARSHIP = 'ADD_SCHOLARSHIP',
    VIEW_SCHOLARSHIP = 'VIEW_SCHOLARSHIP',
    EDIT_SCHOLARSHIP = 'EDIT_SCHOLARSHIP',
    DELETE_SCHOLARSHIP = 'DELETE_SCHOLARSHIP',

    ADD_JOB = 'ADD_JOB',
    VIEW_JOB = 'VIEW_JOB',
    EDIT_JOB = 'EDIT_JOB',
    DELETE_JOB = 'DELETE_JOB',

    ADD_MENTOR_IN_RESIDENCE = 'ADD_MENTOR_IN_RESIDENCE',
    VIEW_MENTOR_IN_RESIDENCE = 'VIEW_MENTOR_IN_RESIDENCE',
    EDIT_MENTOR_IN_RESIDENCE = 'EDIT_MENTOR_IN_RESIDENCE',
    DELETE_MENTOR_IN_RESIDENCE = 'DELETE_MENTOR_IN_RESIDENCE',

    ADD_STUDENT_AMBASSADOR = 'ADD_STUDENT_AMBASSADOR',
    VIEW_STUDENT_AMBASSADOR = 'VIEW_STUDENT_AMBASSADOR',
    EDIT_STUDENT_AMBASSADOR = 'EDIT_STUDENT_AMBASSADOR',
    DELETE_STUDENT_AMBASSADOR = 'DELETE_STUDENT_AMBASSADOR',

    ADD_OPPERTURUNITY = 'ADD_OPPERTURUNITY',
    VIEW_OPPERTURUNITY = 'VIEW_OPPERTURUNITY',
    EDIT_OPPERTURUNITY = 'EDIT_OPPERTURUNITY',
    DELETE_OPPERTURUNITY = 'DELETE_OPPERTURUNITY',
}